### ISSUE TITLE
Zone beam

### ISSUE THREAD

**Issue by normalamron** [blankbhop/btimes#10]
hey dude do you share your zone beam
like this
![Adsız](https://user-images.githubusercontent.com/47062844/54305415-51415780-45d8-11e9-9606-139bf034f374.png)

**Comment by blankbhop** [comment]
Elaborate please.

**Comment by normalamron** [comment]
i want upload that zone beam on shavit timer

**Comment by blankbhop** [comment]
Use the bluelightning zone texture and edit shavit-zones.cfg with the new texture

**Comment by blankbhop** [comment]
Also, next time please open a issue in shavits timer GitHub, the zones are not a matter of my GitHub.

**Comment by normalamron** [comment]
i want as in the picture and i saw bluelightning beam with vtfedit
do you share ?

**Comment by blankbhop** [comment]
Keep this in Shavits timer as I said before, but navigate to materials/sprites/trails in this github, bluelightning is the solid zones, bluelightningscroll3 is the moving version of it seen in most CSGO servers.

**Comment by Nairdaa** [comment]
https://github.com/shavitush/bhoptimer/issues/755

That moron is just incapable of reading with understanding, regardless the fact he's using google translator. Useless to even talk to him.

**Comment by blankbhop** [comment]
Yeah I saw that lol

**Comment by Nairdaa** [comment]
At least I had a good laugh :-) Cheers buddy

**Comment by normalamron** [comment]
@Nairdaa you are fucking retarded

**Comment by blankbhop** [comment]
@normalamron calm down chief
