### ISSUE TITLE
Unreal gun boost

### ISSUE THREAD

**Issue by zeddy1234** [blankbhop/btimes#13]
There's no gun boost possibility in unreal style.
No gun spawns. Mehis tried to add a mag7, which he did, but then gun boost doesn't work.

Any possible fixes?

**Comment by blankbhop** [comment]
Are you using the unrealphys.smx plugin provided? If so it should be working fine, but if not that'd be why.

**Comment by zeddy1234** [comment]
Yes mate, it strips away all weapons you have. Mehis confirmed this too [He's the guy who coded influx timer]

**Comment by skradR** [comment]
I also set up the unrealphys.smx to use weapon_glock. Spawns you with the glock and the correct settings indicated in gunjump.cfg but the boost doesn't work. Mine doesn't strip. Make sure you set your weapon_ weapon choice correctly.

**Comment by blankbhop** [comment]
Try editing [this line](https://github.com/blankbhop/btimes/blob/master/addons/sourcemod/scripting/unrealphys.sp#L191) for the weapon you are having unreal style use, that may fix the stripping issue, I'll try to find out what causes the boosting not to work.

**Comment by blankbhop** [comment]
And make sure your gunjump.cfg is in the correct place.
_sourcemod/configs/gunjump.cfg_
