### ISSUE TITLE
No source code?

### ISSUE THREAD

**Issue by bruno-args** [blankbhop/btimes#2]
Hey, you don't have source code for this? I have alot of ideas for modify this timer.

**Comment by blankbhop** [comment]
I am working on getting the source code, once I get all of the sources I will update the github, the best you can do is share it around and have people send me the sources so I can update the github.

**Comment by bruno-args** [comment]
@blankbhop thanks buddy.

**Comment by blankbhop** [comment]
The source codes I've managed to find so far are now uploaded, I am still working on getting the rest.

**Comment by Cruze03** [comment]
Damn, why leaking though? This would have taken ages to complete..

**Comment by bruno-args** [comment]
> 
> 
> The source codes I've managed to find so far are now uploaded, I am still working on getting the rest.

Thanks! How much times you need to get them all?

**Comment by blankbhop** [comment]
@Cruze03 Leaking this because of personal opinion over the creator of the timer, and I feel like everyone should have access to the timer. 

@pawnlab No clue, no one's given me any others so it could be a long time.

**Comment by bhopppp** [comment]
thx for sharing :)

**Comment by blankbhop** [comment]
Full Source Code added, closing this.
