### ISSUE TITLE
I can't create zone !?

### ISSUE THREAD

**Issue by normalamron** [blankbhop/btimes#6]
I installed on csgo but when i write !zones "[Timer] - Currently loading zones. Please wait." comes out
Please help me i cant create any zone

**Comment by Git-Jamie** [comment]
mapcycle and maplist have to be the same as the maps on the server

**Comment by normalamron** [comment]
@Git-Jamie so ? where are mapcycle and maplist file ?

**Comment by Git-Jamie** [comment]
/CSGO/srv/

**Comment by normalamron** [comment]
@Git-Jamie I can't found, can you help me on discord ?Normal#5271

**Comment by blankbhop** [comment]
Quite the late response, my bad, have you imported the database files and connected it to the server you're running it on?

**Comment by normalamron** [comment]
how can i ?

**Comment by blankbhop** [comment]
If you are unclear about how to use databases, I suggest to use a different timer. Such as Shavits or Influx.
These are found at:
[Shavit](https://github.com/shavitush/bhoptimer)
[Influx](https://influxtimer.com/download)

If you want to use this file please talk to one of your friends who may know how, or learn on your own time.

**Comment by normalamron** [comment]
dude i upload my lan server

**Comment by blankbhop** [comment]
This timer isn't the easiest to set up. As I said, use Shavits or Influx timer if you want a easy to use timer.

**Comment by bhopppp** [comment]
I have the same problem, but i have imported the database files and connected to my server ,but when i create zone it shows loading, i have checked my database but nothing in it, but im certain that nothing wrong in install the timer , i have to use bTimes 1.9. :(

**Comment by normalamron** [comment]
anaskm I have the same problem how can i solve that?
